### ISSUE TITLE
it is the biggest problem for me now

### ISSUE THREAD

**Issue by ReverseSystem001** [kmyid/learn-orientation#1]
The paper you write is very good, I try to configure the environment to achieve it, but I do not know how the code is running. This problem has troubled me for a long time. I am a new bird in this field. and I want to study it . can you tell me the details of the operation. Thank you！Thank you！Thank you！beg beg
beg

**Comment by kmyi** [comment]
Have you tried using this code in conjunction with the benchmark framework?

Should work almost out of the box.

**Comment by ReverseSystem001** [comment]
I have download the benchmark code and  configured both of the environment. But i don’t know how to use them in conjunction with each other. Can you tell me the specific operation procedure. like first... second...I know this is too much, but no one else can help me,The students around me study different directions. so Crazy...       Thank you for answering my question.
and there is another problem,  python2.7 or python3.x, you know they have some differece

**Comment by ReverseSystem001** [comment]
I have a programming language base, but I just started to contact Python and matlab. so I don't know how to run these programs. thank you. and now I'm trying to run these programs. Thanks again

**Comment by kmyi** [comment]
The codes are for Python 2.7. 
Have you tried following the instructions? With this vague information, I cannot really help you.

**Comment by ReverseSystem001** [comment]
After Read the entire code architecture and details of the introduction, Maybe I know how to do it now.thanks .I'm too lazy and impatient.  Aha. Does it work on Linux platform？

**Comment by ReverseSystem001** [comment]
고마워요~

**Comment by kmyi** [comment]
Yes, it should run on both mac and linux. No ideas about windows though.
BTW, I suggest you contact me through e-mail for further discussions. I'm closing the issue now.
